CREATE TABLE BUS_DETAILS(
BUS_ID INT PRIMARY KEY AUTO_INCREMENT,
BUS_NUMBER VARCHAR(10),
OPERATOR_NAME VARCHAR(50),
OPERATOR_NUMBER BIGINT,
TOTAL_SEATS INT,
BASE_FARE INT,
BUS_TYPE VARCHAR(50),
RECLINING_SEATS VARCHAR(3),
CHARGING_POINTS VARCHAR(3),
WIFI VARCHAR(3),
BLANKETS_PILLOWS VARCHAR(3),
SNACKS VARCHAR(3),
MOVIE VARCHAR(3),
READING_LIGHT VARCHAR(3),
TRACK_MY_BUS VARCHAR(3),
M_TICKET VARCHAR(3));

