CREATE TABLE CARD_DETAILS(
CARD_ID INT PRIMARY KEY AUTO_INCREMENT,
USER_ID INT,
CARD_TYPE VARCHAR(50),
CARD_NUMBER VARCHAR(50),
CARDHOLDER_NAME VARCHAR(50),
CARD_EXPIRY VARCHAR(20),
CARD_CVV INT(5),
CARD_BALANCE BIGINT DEFAULT 10000
);

DROP TABLE CARD_DETAILS;

SELECT * FROM CARD_DETAILS;




