SELECT * FROM BOOKING_DETAILS;
SELECT * FROM SEAT_DETAILS;
SELECT * FROM PASSENGER_DETAILS;
SELECT * FROM BUS_DETAILS;
SELECT * FROM TRANSACTION_DETAILS;
SELECT * FROM TRAVEL_DETAILS;
SELECT * FROM USER_CREDENTIALS;
SELECT * FROM CARD_DETAILS;

USE BUS_DB;
