SELECT * FROM SEAT_DETAILS;
SELECT * FROM TRAVEL_DETAILS;
SELECT * FROM USER_CREDENTIALS;
SELECT * FROM TRANSACTION_DETAILS;
SELECT * FROM BOOKING_DETAILS;
USE BUS_DB;
UPDATE TRAVEL_DETAILS SET AVAILABLE_SEATS=50, TEMPORARY_SEATS=0 WHERE TRAVEL_ID=12;
DELETE FROM BOOKING_DETAILS WHERE BOOKING_ID=1;
SELECT * FROM BOOKING_DETAILS;

SELECT * FROM TRANSACTION_DETAILS;
	
SELECT * FROM PASSENGER_DETAILS;
DROP TABLE PASSENGER_DETAILS;
SELECT * FROM TRAVEL_DETAILS;


UPDATE SEAT_DETAILS SET SEAT_STATUS='Temporary' WHERE SEAT_ID = 235;
UPDATE BOOKING_DETAILS SET PAYMENT_STATUS = 'Completed' WHERE BOOKING_ID = 6;

