CREATE TABLE PASSENGER_DETAILS(
PASSENGER_ID INT PRIMARY KEY AUTO_INCREMENT,
BOOKING_ID INT,
TRAVEL_ID INT,
SEAT_NUMBER INT,
FIRST_NAME VARCHAR(20),
LAST_NAME VARCHAR(20),
AGE INT,
GENDER VARCHAR(20)
);