CREATE TABLE SEAT_DETAILS(
SEAT_ID  INT PRIMARY KEY AUTO_INCREMENT,
TRAVEL_ID INT,
BUS_ID INT,
USER_ID INT DEFAULT 0,
SEAT_NUMBER INT,
SEAT_STATUS VARCHAR(10) DEFAULT 'Available',
FOREIGN KEY (TRAVEL_ID) REFERENCES TRAVEL_DETAILS(TRAVEL_ID),
FOREIGN KEY (BUS_ID) REFERENCES BUS_DETAILS(BUS_ID)
);


UPDATE SEAT_DETAILS SET USER_ID=0, SEAT_STATUS = 'Available' WHERE TRAVEL_ID=8 AND SEAT_NUMBER=10;
UPDATE TRAVEL_DETAILS SET AVAILABLE_SEATS=50, TEMPORARY_SEATS=0 WHERE TRAVEL_ID=8;
SELECT * FROM SEAT_DETAILS;
SELECT * FROM TRAVEL_DETAILS;

DROP TABLE SEAT_DETAILS;

DELETE FROM TRAVEL_DETAILS WHERE TRAVEL_ID = 2;