CREATE TABLE SEAT_DETAILS(
SEAT_ID  INT PRIMARY KEY AUTO_INCREMENT,
TRAVEL_ID INT,
BUS_ID INT,
USER_ID INT DEFAULT 0,
SEAT_NUMBER INT,
SEAT_STATUS VARCHAR(10) DEFAULT 'Available',
FOREIGN KEY (TRAVEL_ID) REFERENCES TRAVEL_DETAILS(TRAVEL_ID),
FOREIGN KEY (BUS_ID) REFERENCES BUS_DETAILS(BUS_ID)
);
