CREATE TABLE TRANSACTION_DETAILS(
TRANSACTION_ID INT AUTO_INCREMENT PRIMARY KEY,
USER_ID INT, 
AMOUNT INT,
ACTION VARCHAR(10),
BALANCE INT,
DESCRIPTION VARCHAR(100),
TRANSACTION_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
